echo "2026年8月14日更新0.6.0版"
echo "更新 网页管理命令执行"
echo "修复 运行时间显示问题"
echo "修复 夜间模式覆盖问题"
echo "修复 日志认证成功问题"
echo "更新 systemctl服务"
echo "更新 readme中英介绍"
echo "优化 性能与结构"
echo ""
echo "2026年8月6日更新0.5.0版"
echo "支持 网页修改配置文件"
echo "更新 各种终端参数"
echo "更新 网页后台管理"
echo "更新 日志显示访问IP"
echo "更新 网页系统状态显示"
echo "更新 隐藏文件设置"
echo "更新 排序方式设置"
echo "同步 nlist夜间模式"
echo "优化 日志显示界面"
echo "优化 终端显示"
echo "优化 配置文件"
echo "修复 已知bug"